--- #YAML:1.0
name:                Games-SGF
version:             0.03
abstract:            A general SGF parser
license:             ~
author:              
    - David Whitcomb <whitcode@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    enum:                          0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
